-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 21:11:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab5` DEFAULT CHARACTER SET utf8 ;
USE `lab5` ;

-- -----------------------------------------------------
-- Table `lab5`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5`.`hotel` (
  `id_hotel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `stars` SMALLINT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab5`.`room_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5`.`room_category` (
  `id_room_category` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `square` SMALLINT NOT NULL,
  PRIMARY KEY (`id_room_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab5`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5`.`room` (
  `id_room` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_room_category` INT UNSIGNED NOT NULL,
  `id_hotel` INT UNSIGNED NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_room`, `id_room_category`, `id_hotel`),
  INDEX `fk_room_hotel_idx` (`id_hotel` ASC) VISIBLE,
  INDEX `fk_room_room_category1_idx` (`id_room_category` ASC) VISIBLE,
  CONSTRAINT `fk_room_hotel`
    FOREIGN KEY (`id_hotel`)
    REFERENCES `lab5`.`hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_room_category1`
    FOREIGN KEY (`id_room_category`)
    REFERENCES `lab5`.`room_category` (`id_room_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab5`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5`.`client` (
  `id_client` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab5`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5`.`booking` (
  `id_booking` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_client` INT UNSIGNED NOT NULL,
  `booking_date` DATE NOT NULL,
  PRIMARY KEY (`id_booking`, `id_client`),
  INDEX `fk_booking_client1_idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT `fk_booking_client1`
    FOREIGN KEY (`id_client`)
    REFERENCES `lab5`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab5`.`room_in_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5`.`room_in_booking` (
  `id_room_in_booking` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_booking` INT UNSIGNED NOT NULL,
  `id_room` INT UNSIGNED NOT NULL,
  `checkin_date` DATE NOT NULL,
  `checkout_date` DATE NOT NULL,
  PRIMARY KEY (`id_room_in_booking`, `id_booking`, `id_room`),
  INDEX `fk_room_in_booking_room1_idx` (`id_room` ASC) VISIBLE,
  INDEX `fk_room_in_booking_booking1_idx` (`id_booking` ASC) VISIBLE,
  CONSTRAINT `fk_room_in_booking_room1`
    FOREIGN KEY (`id_room`)
    REFERENCES `lab5`.`room` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_in_booking_booking1`
    FOREIGN KEY (`id_booking`)
    REFERENCES `lab5`.`booking` (`id_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
